name = input("Given name: ")
fname = input("Family name: ")
address = input("Street address: ")
city_postcode = input("City and postal code: ")
print(name + " " + fname)
print(address)
print(city_postcode)